apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
  - port: 3000
    name: grafana
    targetPort: 3000
    protocol: TCP
    nodePort: 30102
  selector:
    app: grafana
  type: NodePort