apiVersion: v1
kind: Service
metadata:
  name: tyk-gateway
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002
    protocol: TCP
  selector:
    app: tyk-gateway
  type: LoadBalancer